### ISSUE TITLE
Common TODO list

### ISSUE THREAD

**Issue by icebob** [icebob/vue-express-mongo-boilerplate#11]
* [ ] service based modules like in FeatherJS ( https://blog.feathersjs.com/using-feathersjs-to-make-your-existing-api-real-time-813f7c3fd892#.stfdjx3cg ) 
* [ ] create posts page with GraphQL with mutations
* [ ] rewrite account.js response handlers
* [ ] localized emails
* [ ] check https://github.com/keystonejs/keystone
* [ ] check https://github.com/madhums/node-express-mongoose-demo/blob/master/config/express.js
* [ ] add unit tests with mocha, chai, sinon
* [ ] add E2E test with nightwatch
* [ ] design styles: dropdown ( https://jsfiddle.net/Cerebrl/uhykY/ ), tabs ( http://v4-alpha.getbootstrap.com/components/card/ )
* [ ] pagination to dataTable
* [ ] update GrahpQL Apollo Stack
* [ ] implement user notification
* [ ] implement user messages
* [ ] implement user profile page
* [ ] add language selection
